- Documentation/Changelog.md
- Python/tdw/tdw_utils.py
- Fixed: `validate_amazon_s3()` raises exceptions even if credentials are valid.
> Fixed validate_amazon_s3()

- Documentation/Changelog.md
- Documentation/api/command_api.md
| Command                               | Description                                       |
| ------------------------------------- | ------------------------------------------------------------ |
| `add_position_marker` | Create a non-physics, non-interactive sphere to mark a position in the scene. |
| `remove_position_markers` | Remove all position markers from the scene. |
> Position markers

- Documentation/Changelog.md
- Python/tdw/librarian.py
- Fixed: Relative URLs in records don't work as expected.
> fixed relative urls

- Documentation/Changelog.md
- Documentation/python/tdw_utils.md
- Python/tdw/tdw_utils.py
- Added: `quaternion_to_euler_angles()` Convert a quaternion to Euler angles.
> Quaternion to euler

- Documentation/Changelog.md
- Documentation/python/object_init_data.md
- Python/setup.py
- Python/tdw/object_init_data.py
Parameter `rotation` in `TransformInitData` and its subclasses can be Euler angles or a quaternion.
> Object init data eulers

- Documentation/Changelog.md
- Documentation/python/tdw_utils.md
- Python/tdw/tdw_utils.py
- Added: `tdw.tdw_utils.QuaternionUtils` Utility functions for quaternions.
- Moved `euler_to_quaternion()` to `QuaternionUtils`
- Renamed function to `euler_angles_to_quaternion()`
- Parameter `euler` is a numpy array (was a tuple).
- Return type is a numpy array (was a list of floats).
- Moved `quaternion_to_euler_angles()` to `QuaternionUtils`
> QuaternionUtils

- Documentation/Changelog.md
- Documentation/api/command_api.md
| Command           | Modification                            |
| ----------------- | --------------------------------------- |
| `send_spherecast` | Added optional parameter `id`.          |
| `send_raycast`    | Renamed parameter `raycast_id` to `id`. |
> spherecast id

- Documentation/Changelog.md
Fixed: Various graphics glitches when enabling/disabling cameras.
> Fixed bug with image sensor enable/disable

- Documentation/Changelog.md
- Documentation/api/command_api.md
| Command                   | Description                                                  |
| ------------------------- | ------------------------------------------------------------ |
| `set_reverb_space_simple` | Added optional parameters `min_room_volume` and `max_room_volume`. |
> Added optional volume parameters to set_reverb_space_simple

- Documentation/Changelog.md
- Python/tdw/metadata_libraries/models_core.json
- Python/tdw/py_impact/objects.csv
- Added: 4ft_wood_shelving, 5ft_shelf_metal, 5ft_wood_shelving, 6ft_shelf_metal, 6ft_wood_shelving
> Minor audio data

- Documentation/Changelog.md
- Documentation/api/command_api.md
Closes #151 
| Command        | Description                                                  |
| -------------- | ------------------------------------------------------------ |
| `add_fixed_joint` | Un-deprecated because it's still being used                  |
> undeprecated add_fixed_joint

- Python/tdw/metadata_libraries/models_core.json
Minor changes to the model library
> Model pipeline

- Documentation/Changelog.md
- Documentation/api/command_api.md
| Command                  | Description                              |
| ------------------------ | ---------------------------------------- |
| `apply_torque_to_object` | Apply a torque to an object's rigidbody. |
> Added: apply_torque_to_object

- Python/tdw/controller.py
Added the option for controller to pass port to build, so we can run multiple controllers in parallel which really speeds up scenario design
> controller can now pass port to build

- Documentation/Changelog.md
- Documentation/api/command_api.md
- Documentation/upgrade_guides/v1.7_to_v1.8.md
| Command                           | Description                                                  |
| --------------------------------- | ------------------------------------------------------------ |
| `set_robot_joint_physic_material` | Set the physic material of a robot joint.                    |
> Set robot joint physic material

- Documentation/Changelog.md
Fixed a potential memory leak in `set_physic_material` and `set_avatar_physic_material`.
> Fixed a potential memory leak due to not destroying the old physic material

- Documentation/Changelog.md
- Python/setup.py
- Python/tdw/metadata_libraries/models_core.json
- Python/tdw/py_impact/objects.csv
Added distractor models from models_full.json to models_core.json
> Distractor models

- Documentation/Changelog.md
> Fixed Resonance Audio on OS X

- Documentation/Changelog.md
> Fixed rare avatar ID/object ID clash

- Documentation/Changelog.md
- Python/tdw/scene/room_bounds.py
- Python/tdw/scene/scene_bounds.py
- (Backend): Added `SceneBounds` and `RoomBounds`. Convenient wrapper classes for scenes and room environments.
> Added: SceneBounds and RoomBounds

- Documentation/api/output_data.md
- Python/tdw/FBOutput/MagnebotWheels.py
- Python/tdw/output_data.py
Added boolean `get_success()` to `MagnebotWheels`
> Magnebot wheels success

- Documentation/Changelog.md
- Documentation/api/output_data.md
- Python/tdw/FBOutput/RigidbodyData.py
- Python/tdw/output_data.py
| Output Data          | Modification                   |
| -------------------- | ------------------------------ |
| `Rigidbodies`        | Added: `get_kinematic()`       |
> Added: Rigidbodies.get_kinematic()

- Documentation/api/command_api.md
- Python/setup.py
Added internal links to command_api.md
> Added internal links to command API

- Documentation/Changelog.md
- Documentation/python/quaternion_utils.md
- Documentation/python/tdw_utils.md
- Python/tdw/quaternion_utils.py
- Python/tdw/tdw_utils.py
- Added: `TDWUtils.bytes_to_megabytes(b)` Convert a quantity of bytes to a quantity of megabytes.
- Added: `QuaternionUtils.is_left_of(origin, target, forward)` Returns True if `target` is to the left of `origin` otherwise returns False.
> Added TDWUtils.bytes_to_megabytes() and QuaternionUtils.is_left_of()

- Documentation/Changelog.md
- Python/setup.py
- Python/tdw/metadata_libraries/models_core.json
- Python/tdw/physics_audio/objects.csv
- Added to `models_core.json`: large_mesh_basket, trashbin, b04_11_02_041, b04_kevin_reilly_pattern_floor_lamp, duncan_floor_lamp_crate_and_barrel, b03_restoration_hardware_pedestal_salvaged_round_tables, b04_03_077, gas_stove
> Moved some models from models_full.json to models_core.json

- Documentation/Changelog.md
- Documentation/lessons/navigation/occupancy_maps.md
- Documentation/python/add_ons/occupancy_map.md
- Python/tdw/add_ons/occupancy_map.py
- Added: `OccupancyMap.reset()` Reset the occupancy map. Call this when resetting a scene.
> Added OccupancyMap.reset()

- Documentation/Changelog.md
- Python/setup.py
- Python/tdw/asset_bundle_creator.py
- Python/tdw/metadata_libraries/models_core.json
- Added models `models_core.json` and `models_full.json`: b03\_aluminum\_pan\_composite, b03\_ka90ivi20r\_2013\_\_vray\_composite, b04\_db\_apps\_tech\_08\_03\_composite, cabinet\_24\_single\_door\_wood\_beech\_honey\_composite, cabinet\_24\_single\_door\_wood\_oak\_white\_composite, cabinet\_24\_two\_door\_wood\_beech\_honey\_composite, cabinet\_24\_two\_door\_wood\_oak\_white\_composite, cabinet\_full\_height\_wood\_beech\_honey\_composite, cabinet\_full\_height\_wood\_oak\_white\_composite, db\_apps\_tech\_08\_10\_composite, dishwasher\_4\_composite, gas\_stove\_composite, kenmore\_refr\_74049\_composite, pot\_composite, sink\_cabinet\_unit\_wood\_beech\_honey\_chrome\_composite, sink\_cabinet\_unit\_wood\_beech\_honey\_porcelain\_composite, …
> New composite models

- Documentation/Changelog.md
- Documentation/lessons/flex/fluid_and_source.md
- Python/example_controllers/flex/fluid.py
Fixed: TypeError in `fluid.py`
> Fluid controller fix

- Documentation/Changelog.md
- Documentation/lessons/objects_and_scenes/floorplans.md
- Python/example_controllers/objects_and_scenes/floorplan.py
> Fixed: floorplan.py doesn't hide the roof

- Documentation/Changelog.md
- Documentation/python/controller.md
- Python/tdw/controller.py
| Document                        | Modification                                                 |
| ------------------------------- | ------------------------------------------------------------ |
| `python/controller.md`          | Clarified how the wrapper functions that return commands work. |
> Controller command doc

- Documentation/Changelog.md
- Python/setup.py
> Fixed: OS X build doesn't use OpenGL

- Documentation/Changelog.md
- Python/tdw/metadata_libraries/models_core.json
- Python/tdw/metadata_libraries/models_special.json
- Added models to `models_core.json` and `models_full.json`: b03_12_06_027_composite, b04_wallmounted_soap_dispenser_composite, vray_077_composite, vray_083_composite, vray_084_composite, vray_085_composite
- Added models to `models_special.json`: stairs_one, stairs_two
> New models

- Documentation/Changelog.md
- Python/setup.py
- Python/tdw/metadata_libraries/models_core.json
- Python/tdw/physics_audio/objects.csv
- Added to `models_core.json`: b01_trumpet, b03_trumpet_vray, b03_piccolo_trumpet_vray, b04_b200003_01, b04_baterijska_busilica, dewalt_compact_drill_vray, b03_hair_comb_2010, b04_baseball_bat, b05_racket, dumb-bell_2010
> Added models for the ABC Game

- Documentation/Changelog.md
- Documentation/python/add_ons/ui.md
- Python/setup.py
- Python/tdw/add_ons/ui.py
Added `ui.add_loading_screen(text, text_size)` A macro function for loading screens.  Combines `self.add_image()` (adds a black background) and `self.add_text()` (adds a loading message).
> Added: ui.add_loading_screen()

- Documentation/Changelog.md
- Documentation/api/command_api.md
Added: `set_visual_material_smoothness`
> set_visual_material_smoothness

- Documentation/Changelog.md
- Documentation/lessons/core_concepts/add_ons.md
- Documentation/python/add_ons/add_on.md
- Documentation/python/add_ons/audio_initializer.md
- Documentation/python/add_ons/audio_initializer_base.md
- Documentation/python/add_ons/collision_manager.md
- Documentation/python/add_ons/composite_object_manager.md
- Documentation/python/add_ons/container_manager.md
- Documentation/python/add_ons/first_person_avatar.md
- Documentation/python/add_ons/floorplan.md
- Documentation/python/add_ons/image_capture.md
- Documentation/python/add_ons/interior_scene_lighting.md
- Documentation/python/add_ons/keyboard.md
- Documentation/python/add_ons/logger.md
- Documentation/python/add_ons/mouse.md
- Documentation/python/add_ons/obi.md
- Documentation/python/add_ons/object_manager.md
- Documentation/python/add_ons/occupancy_map.md
- Documentation/python/add_ons/oculus_touch.md
- Documentation/python/add_ons/physics_audio_recorder.md
- Documentation/python/add_ons/proc_gen_kitchen.md
- Documentation/python/add_ons/resonance_audio_initializer.md
- Documentation/python/add_ons/step_physics.md
- Documentation/python/add_ons/trigger_collision_manager.md
- Documentation/python/add_ons/ui.md
- Documentation/python/add_ons/vr.md
- Python/setup.py
- Python/tdw/add_ons/add_on.py
[Read this](https://github.com/threedworld-mit/tdw/blob/add_on_communicate/Documentation/python/add_ons/add_on.md)
> Clarified in all of the API documents for AddOn subclasses how and when on_send(resp) gets called

- Documentation/Changelog.md
- Python/setup.py
- Python/tdw/metadata_libraries/models_core.json
- Added to `models_core.json`: b05_fire_extinguisher, b04_fireextinguisher, fire_extinguisher, fire_extinguisher_(max2014)
> Added fire extinguishers

- Documentation/Changelog.md
- Documentation/python/add_ons/replicant.md
- Python/example_controllers/replicant/carry_couch.py
- Python/setup.py
- Python/tdw/add_ons/replicant.py
- Python/tdw/replicant/actions/action.py
- Fixed: Replicant motions are glitchy at high framerates. The `Replicant` now has a `target_framerate` parameter that by default caps the simulation at 100 FPS, making it far more likely to run as expected.
- Fixed: Replicant doesn't work as expected at low framerates.
> Fixed carry_couch.py

- Documentation/Changelog.md
- Documentation/python/quaternion_utils.md
- Python/setup.py
- Python/tdw/quaternion_utils.py
- Fixed: `QuaternionUtils.euler_angles_to_quaternion(euler)` and `QuaternionUtils.quaternion_to_euler_angles(quaternion)` return incorrect values.
- (Backend) Fixed the type hinting of `QuaternionUtils` (np.ndarray instead of np.array).
1. Checkout to the branch `quaternions` in this repo (not TDWBase).
2. Run the controller.
This controller adds a cube to the scene. For 100 frames, the cube is randomly rotated. The build returns `Transforms`, which includes the object's quaternion, and `EulerAngles`. The quaternion and Euler angles are stored per frame.
Next, TDW's `QuaternionUtils` takes the returned Euler angles and converts it to a quaternion, and it takes the returned quaternion and converts it to Euler angles. The values are rounded to 4 decimal places and compared to the output …
> Quaternions

- Documentation/Changelog.md
- A *very* small speed improvement loading local asset bundles (as opposed to downloading them)
> Improved speed of loading local asset bundles

- Documentation/lessons/visual_perception/overview.md
> fixed example code snippet

- Documentation/Changelog.md
- Documentation/api/output_data.md
Closes #623 
| Document | Modification |
| --- | --- |
| `api/output_data.md` | Fixed missing link in ScreenPosition. |
> Screen position documentation

- Documentation/api/command_api.md
> fixed rotate_object_by documentation

- Documentation/Changelog.md
- Python/setup.py
- Python/tdw/add_ons/proc_gen_kitchen.py
- Python/tdw/add_ons/robot_arm.py
- Python/tdw/backend/performance_benchmark_controller.py
- Python/tdw/ikpy/chain.py
- Python/tdw/ikpy/source.txt
- Python/tdw/output_data.py
- Python/tdw/proc_gen/arrangements/arrangement.py
- Python/tdw/proc_gen/arrangements/basket.py
- Python/tdw/proc_gen/arrangements/cup_and_coaster.py
- Python/tdw/proc_gen/arrangements/dishwasher.py
- Python/tdw/proc_gen/arrangements/kitchen_cabinet.py
- Python/tdw/proc_gen/arrangements/painting.py
- Python/tdw/proc_gen/arrangements/shelf.py
- Python/tdw/proc_gen/arrangements/side_table.py
- Python/tdw/proc_gen/arrangements/stool.py
- Python/tdw/proc_gen/arrangements/stove.py
- Python/tdw/proc_gen/arrangements/suitcase.py
- Python/tdw/remote_build_launcher.py
- Python/tdw/tdw_utils.py
- Python/tdw/wheelchair_replicant/actions/move_by.py
- Python/tdw/wheelchair_replicant/actions/turn_by.py
- Fixed: Some parts of TDW don't work on Python 3.10 or newer. (TDW should now work on any version of Python newer than 3.6)
> Fixed: Some parts of TDW don't work on Python 3.10 or newer.

- Documentation/Changelog.md
- Python/setup.py
- Python/tdw/metadata_libraries/scenes.json
- Added room metadata to `tdw_room`
- Added: `tdw_room_4x5` A 4x5 grid of tdw_room
> tdw_room_4x5

- Documentation/Changelog.md
- Documentation/api/command_api.md
| Command | Description |
| --- | --- |
| `set_ui_color` | Set the color of a UI image or text. |
> Added: set_ui_color

- Python/tdw/quaternion_utils.py
add world_to_local_rotation function in QuaternionUtils to convert world rotation vector to local rotation vector.
> add world_to_local_rotation function in QuaternionUtils
