Python/tdw/release/pypi.py
I'm following the "getting started" guide, but don't want to `sudo pip install` things, so am running this in a virtualenv. It doesn't work because using `shell=True`, removing it works. I don't think you actually need `shell=True` as you're just executing a command, not using redirects/pipes/etc. in the command itself.
Also, a second problem that I'm not solving in this PR, the binary it created didn't have execute rights:
```
><((("> python test.py
Your installed tdw Python module is up to date with PyPi.
Couldn't find build at /home/beyer/tdw_build/TDW/TDW.x86_64
Downloading now...
Downloaded the build.
Saved the .zip file.
Extracted the .zip file to: /home/beyer/tdw_build
Deleted the .zip file.
Traceback (most recent call last):
File "test.py", line 3, in <module>
c = Controller() …
```
=> Don't use shell=True so it works in virtualenv

Documentation/getting_started.md
There were a few mistakes, I guess because of version updates?
1. Use `models_core.json` so it works for everybody.
2. We need to extract the y coordinate from `get_top`.
3. Use the `"ids"` parameter to `send_bounds` to simplify code a little.
Fixes #6 
One more thing: The tutorial says that `img` is now a numpy image. That is not true however, and one needs to do a bit more work to get a numpy array out of it or save it, might be worth updating that too.
=> Multiple small fixes on Getting Started example

Documentation/Changelog.md, Python/tdw/controller.py
- Don't check the version of the build or download a new build if `launch_build == False`
- Edited the message for when you are using code from the tdw repo that is ahead of PyPi.
=> Check version launch build

Documentation/Changelog.md, Documentation/getting_started.md, Documentation/python/example_controllers.md, Python/example_controllers/getting_started.py
- Added `getting_started.py` This is the controller in the Getting Started guide.
| Document | Modification |
| --- | --- |
| `getting_started.md` | The initial test for new users is `getting_started.py` instead of `objects_and_images.py`.<br>Added a link to `getting_started.py`.<br>Edited the example controller code (`getting_started.py`) for clarity. |
=> Getting started controller

Documentation/Changelog.md, Python/tdw/controller.py
How to test:
1. `git fetch`
2. `git checkout controller_popen_shell`
3. `cd Python/example_controllers`
4. `py -3 minimal.py`
=> Use shell=True when launching the build in Windows

Python/tdw/controller.py
Fixed a bug where launching TDW via Popen in Windows resulted in a WinError 193.
Solution: Encapsulate launch args in a list.
=> Revert popen shell

Documentation/api/command_api.md
| Command | Description |
| --- | --- |
| `set_floorplan_roof` |  Show or hide the roof of a floorplan scene. This command only works if the current scene is a floorplan added via the add_scene command: "floorplan_1a", "floorplan_4b", etc. |
=> set_floorplan_roof

Documentation/Changelog.md
- Fixed: The objects created by `add_position_marker` initially have colliders, potentially causing physics interactions.
=> Position marker colliders

Documentation/Changelog.md, Documentation/python/tdw_utils.md, Python/setup.py, Python/tdw/tdw_utils.py
- Added: `color_to_hashable()`. Convert a color to a hashable integer.
- Added: `hashable_to_color()`. Convert a hashable integer to a color.
=> Added functions for hashing and un-hashing colors

Documentation/Changelog.md, Python/benchmarking/benchmarker.py, Python/benchmarking/do_nothing.py, Python/benchmarking/flex_benchmarker.py, Python/benchmarking/real_world_benchmarker.py, Python/setup.py
- `benchmarker.py` no longer automatically launches the build.
=> benchmarker no longer launches build

Documentation/Changelog.md, Python/tdw/tdw_utils.py
Fixed: `Bounds` output data is incorrect.
=> Fixed: Bounds data is inaccurate

Documentation/Changelog.md, Documentation/python/keyboard_controller.md, Python/example_controllers/keyboard_controls.py, Python/setup.py, Python/tdw/keyboard_controller.py
- Removed `keyboard` as a required module.
- Controller now uses `Keyboard` output data from the simulator to detect keyboard input instead of the Python `keyboard` module, which is less reliable and doesn't work on OS X.
=> Replaced Python keyboard module with Unity keyboard listeners

Documentation/Changelog.md, Documentation/python/tdw_utils.md, Python/setup.py, Python/tdw/tdw_utils.py
- Added: `get_y_angle()` The angle between two quaternions in degrees around the y axis.
=> Added: QuaternionUtils.get_y_angle()

Documentation/Changelog.md, Documentation/getting_started.md
| Document             | Description                                                  |
| -------------------- | ------------------------------------------------------------ |
| `getting_started.md` | Fixed: Instructions for how to run TDW on a remote server are incorrect. |
=> Fixed: instructions for how to run on a remote server are incorrect

Documentation/Changelog.md, Documentation/api/command_api.md
| Command        | Description                                                  |
| -------------- | ------------------------------------------------------------ |
| `send_version` | Added optional parameter `log` to log the TDW version in the Player or Editor log (default value is True). |
=> Added optional log parameter to send_version

Documentation/Changelog.md, Documentation/misc_frontend/impact_sounds.md, Python/setup.py, Python/tdw/py_impact.py
- Fixed: PyImpact sometimes creates a droning audio effect. To prevent this, PyImpact will ignore collision events if the same pair of objects registers an `enter` and `stay` collision event on the same frame.
| Document           | Description                                                  |
| ------------------ | ------------------------------------------------------------ |
| `impact_sounds.md` | Added a section and code example for how to prevent audio droning. |
=> Added code to PyImpact to optionally prevent a droning audio effect

Documentation/misc_frontend/robots.md
The presence of a space broke Github renderer. Actually, Github is using a slug with hyphen instead of spaces.
=> fix(docs): link was erroneous

Documentation/Changelog.md, Documentation/misc_frontend/osx.md, Documentation/python/controller.md, Python/tdw/controller.py, Python/tdw/release/build.py
- **Fixed: Can't launch TDW.app by double-clicking it.** If you download the build from the Releases page on the repo, you can run `setup.sh` (located in the same directory as `TDW.app`). If you download the build by launching a controller, i.e. `c = Controller()`, the controller will automatically fix TDW.app before launching it.
=> Launch setup.sh to fix .app errors

Documentation/Changelog.md, Python/setup.py, Python/tdw/tdw_utils.py
- Added: `TDWUtils.get_bounds_extents()` Returns the width, length, height of an object's bounds.
=> Added: TDWUtils.get_bounds_extents

Python/setup.py, Python/tdw/controller.py
Fixed: The build process heartbeat can listen for the wrong build on the wrong port.
=> Build process port

Python/setup.py
For each model just moved from models_full to models_core, the URLs in _models_full.json_ have been fixed. They pointed to the "old" private asset bundle and now point to the public asset bundles.
=> Replaced URLs with public URLs

Python/use_cases/single_object/single_object.py
Current code leads to incorrect number of train images generated
=> Fixing an off-by-one error in single_object

Documentation/Changelog.md, Python/setup.py, Python/tdw/tdw_utils.py
- Fixed: RuntimeWarning in `QuaternionUtils.get_y_angle()` due to a NaN value.
=> Fixed a NaN error in QuaternionUtils

Documentation/Changelog.md, Documentation/api/output_data.md, Python/tdw/FBOutput/Overlap.py, Python/tdw/output_data.py
| Output Data | Modification                                                 |
| ----------- | ------------------------------------------------------------ |
| `Overlap`   | Added: `get_walls()`. Returns True if there is a non-floor environment object in the overlap (such as a wall). |
=> Added get_walls() to Overlap output data

Documentation/Changelog.md, Documentation/python/controller.md, Python/setup.py, Python/tdw/controller.py
- Fixed: As of a few updates ago, the controller often sends non-unique object IDs. We are still trying to determine what changed in the build's code, but in the meantime, `Controller.get_unique_id()` will always return a unique ID.
- Added `Controller.reset_unique_id()` to prevent overflow errors.
=> Fixed: object IDs are often non-unique

Documentation/Changelog.md, Documentation/api/command_api.md
| Command | Description |
| --- | --- |
| `parent_object_to_avatar`          | Parent an object to an avatar.                               |
| `unparent_object`      | Unparent an object from its current parent.                          |
=> Added: parent_object_to_avatar and unparent_object_from_avatar

Documentation/Changelog.md, Documentation/python/build.md, Documentation/python/pypi.md, Python/setup.py, Python/tdw/release/build.py, Python/tdw/release/pypi.py
- Added optional parameter `check_head` to `get_url()`. If True, check the HTTP headers to make sure that the release exists.
- Added: `required_tdw_version_is_installed(required_version, build_version)` Check whether the correct version of TDW is installed. This is useful for other modules such as the Magnebot API that rely on certain versions of TDW.
=> Added: PyPi.required_tdw_version_is_installed()

Documentation/Changelog.md, Documentation/api/command_api.md
| Command               | Modification                                                 |
| --------------------- | ------------------------------------------------------------ |
| `use_pre_signed_urls` | Default value for all Linux distros is True (was True only for Ubuntu 20 and otherwise False). |
- Fixed: race condition when requesting collision data for objects that have just been destroyed.
=> Cached object collisions

Documentation/Changelog.md, Documentation/python/pypi.md, Python/tdw/release/pypi.py
- (Backend) Added optional parameter `comparison` to `PyPi.required_tdw_version_is_installed()`. Options: `"equals"`, `"greater_than"`, and `"greater_than_or_equals"`.
=> Added optional parameter comparison to required_tdw_version_is_installed()

Documentation/Changelog.md, Documentation/python/controller.md, Documentation/upgrade_guides/v1.8_to_v1.9.md, Python/tdw/controller.py
**Removed `Controller.start()`** 
This function used to send a command to initialize a scene in TDW. Now, that command is sent automatically in the Controller constructor.
Note that this PR updates the API doc, the upgrade doc, and the changelog, but none of the tutorials or example controllers. Those will be addressed in a separate PR off of the documentation_v2 branch (as opposed to this PR which is off of the v1.9_wip branch).
In v1.8:
```python
from tdw.controller import Controller
from tdw.tdw_utils import TDWUtils
c = Controller()
c.start()
c.communicate(TDWUtils.create_empty_room(12, 12))
```
In v1.9:
```python
from tdw.controller import Controller
from tdw.tdw_utils import TDWUtils
c = Controller()
c.communicate(TDWUtils.create_empty_room(12, 12))
```
=> Removed Controller.start()

Documentation/Changelog.md
1. In `TDWBase`, `git fetch` and `git checkout set_composite_object_kinematic`
2. Write a controller that adds a composite object + `set_kinematic_state`. Set `launch_build=False`
3. Launch the controller
4. Launch the build in Unity Editor
Result: The composite object doesn't move.
=> Fixed: set_kinematic_state only affects root of composite objects

Documentation/Changelog.md, Python/tdw/physics_audio/collision_audio_event.py
- Fixed: `PyImpact` seems to be "missing" impact sounds because roll sounds haven't been implemented yet. Now, all "roll" events are handled as "impact events".
=> Fixed: Roll events are now registered as impact events

Documentation/Changelog.md, Documentation/lessons/3d_models/custom_models.md
This is a revision of [this PR](https://github.com/threedworld-mit/tdw/pull/329) that uses the JSON deserialization syntax used elsewhere in the documentation, i.e. using `Path.read_text()`
=> Fixed example controllers in custom_models.md

Documentation/Changelog.md, Documentation/python/tdw_utils.md, Python/setup.py, Python/tdw/tdw_utils.py
Added: `TDWUtils.get_circle_mask(arr, row, column, radius)`. Get elements in an array within a circle.
=> Added: TDWUtils.get_circle_mask()

Documentation/Changelog.md, Python/tdw/tdw_utils.py
See: https://github.com/threedworld-mit/tdw/pull/332/files
This PR fixes the bug in `TDWUtils` as opposed to `ImageCapture`
Example controller:
```python
from tdw.controller import Controller
from tdw.tdw_utils import TDWUtils
from tdw.add_ons.third_person_camera import ThirdPersonCamera
from tdw.add_ons.image_capture import ImageCapture
from tdw.backend.paths import EXAMPLE_CONTROLLER_OUTPUT_PATH
c = Controller()
camera = ThirdPersonCamera(position={"x": 0, "y": 1, "z": 0},
avatar_id="a")
capture = ImageCapture(avatar_ids=["a"],
pass_masks=["_img", "_depth"],
path=EXAMPLE_CONTROLLER_OUTPUT_PATH.joinpath("depth_pil"))
c.add_ons.extend([camera, capture])
c.communicate(TDWUtils.create_empty_room(12, 12))
capture.get_pil_images()["a"]["_depth"].show()
c.communicate({"$type": "terminate"}) …
```
=> Fixed: TDWUtils.get_pil_images() doesn't work for _depth or _depth_simple

Documentation/Changelog.md, Documentation/lessons/3d_models/custom_models.md
| Document                             | Modification                                                 |
| ------------------------------------ | ------------------------------------------------------------ |
| `lessons/3d_models/custom_models.md` | Added a section regarding .fbx unit scales; .fbx files must be in meters. |
=> Added a section about exporting fbx files in meters

Documentation/Changelog.md, Documentation/lessons/3d_models/custom_models.md, Documentation/lessons/robots/custom_robots.md, Documentation/python/asset_bundle_creator.md, Documentation/python/asset_bundle_creator_base.md, Documentation/python/robot_creator.md, Python/setup.py, Python/tdw/asset_bundle_creator.py, Python/tdw/asset_bundle_creator_base.py, Python/tdw/robot_creator.py
- Added optional parameter `unity_editor_path` to the `AssetBundleCreator`constructor to optionally explicitly set the path to the Unity Editor executable.
- Added: `AssetBundleCreator.cleanup()` Clean up intermediary files.
- Added optional parameter `unity_editor_path` to the `RobotCreator`constructor to optionally explicitly set the path to the Unity Editor executable.
- Changed the names of all undocumented fields in `AssetBundleCreator` and `RobotCreator` to private (added an `_` to the start of the variable names).
- Added optional parameters `description_infix` and `branch` to `RobotCreator.create_asset_bundles()` to handle unexpected .urdf URLs.
| Document                             | Modification                                                 |
| …
=> Handle unexpected paths in AssetBundleCreator and RobotCreator

Documentation/Changelog.md, Python/setup.py, Python/tdw/metadata_libraries/robots.json
Closes #341 
See: https://github.com/fetchrobotics/fetch_ros/issues/160
- Fixed various issues with fetch robot's wheels:
- Added four revolute joints for the non-motorized wheels: non_motorized_wheel_front_left, non_motorized_wheel_front_right, non_motorized_wheel_back_left, non_motorized_wheel_back_right.
- Removed bellows_link_2 as a joint (it was causing fetch to turn and was otherwise non-functional) but kept the visual mesh.
- Removed estop_link as a joint (it didn't do anything) but kept the visual mesh.
- Removed laser_link fixed joint and visual mesh (it didn't do anything).
To test, run this controller:
```python
from tdw.controller import Controller
from tdw.tdw_utils import TDWUtils
from tdw.add_ons.robot import Robot
c = Controller()
r = Robot(robot_id=0, name="fetch", …
```
=> Fixed fetch robot's wheels

Documentation/Changelog.md, Python/setup.py, Python/tdw/metadata_libraries/models_core.json
- Flagged models as do_not_use in `models_full.json`: b03_radiator_old, b05_ikea_nutid_side_by_side_refrigerator
- Added to `models_core.json`:  b03_radiator_alum_12, b05_castironradiator, radiator_pub_2015, fredericia_spine_stool_1, mater_high_stool_al_69, tolix_bar_stool
=> Full to core

Documentation/Changelog.md, Documentation/lessons/camera/rotation.md, Documentation/python/add_ons/third_person_camera.md, Python/tdw/add_ons/third_person_camera.py
- Replaced `ThirdPersonCamera.look_at_target` with  `ThirdPersonCamera.look_at(target)` in order to allow the camera to look at a target on the next `communicate()` call.
=> Added: ThirdPersonCamera.look_at(target)

Documentation/Changelog.md, Documentation/lessons/audio/record_audio.md, Documentation/lessons/objects_and_scenes/materials_textures_colors.md, Python/setup.py, Python/tdw/audio_utils.py
- Fixed: `AudioUtils` (and, by extension, `PhysicsAudioRecorder`) doesn't work on OS X.
| Document                               | Modification                                                 |
| -------------------------------------- | ------------------------------------------------------------ |
| `lessons/objects_and_scenes/materials_textures_colords.md` | Added a missing line of code in one of the examples.         |
| `lessons/audio/recording_audio.md`                         | Added instructions for installing fmedia on all platforms (including OS X) |
=> Fixed: fmedia doesn't work on OS X

Documentation/Changelog.md, Documentation/api/command_api.md, Documentation/lessons/physx/composite_objects.md
| Command                      | Description                          |
| ---------------------------- | ------------------------------------ |
| `set_motor_target_velocity`  | Set the target velocity of a motor.  |
| `set_motor_force`            | Set the force of a motor.            |
| Command      | Reason                                                       |
| ------------ | ------------------------------------------------------------ |
| `set_motor`  | Replaced with `set_motor_target_velocity` and `set_motor_force` |
=> Added motor commands

Documentation/Changelog.md, Documentation/lessons/vr/oculus_touch.md, Documentation/python/add_ons/oculus_touch.md, Python/tdw/add_ons/oculus_touch.py
- By default, the `OculusTouch` add-on will set the rig's hands and all graspable objects to the "discrete" collision detection mode.
- Updated the Oculus Touch doc with a section re: physics glitches
=> Oculus Touch add-on auto-sets Discrete collision detection mode

Documentation/Changelog.md, Documentation/api/command_api.md, Documentation/lessons/non_physics/overview.md, Documentation/lessons/non_physics/textured_quads.md
| Command                          | Description                                                  |
| -------------------------------- | ------------------------------------------------------------ |
| `parent_textured_quad_to_object` | Parent a textured quad to an object in the scene. The textured quad will always be at a fixed local position and rotation relative to the object. |
| `unparent_textured_quad`         | Unparent a textured quad from an object.                     |
| Document                                | Modification                                                 |
| --------------------------------------- | ------------------------------------------------------------ |
| `lessons/non_physics/textured_quads.md` | Clarified  that only textured quad commands work with …
=> Added commands to parent and unparent textured quads

Documentation/Changelog.md, Documentation/python/add_ons/ui.md, Python/setup.py, Python/tdw/add_ons/ui.py
- Added optional field `plane_distance` to `ui.attach_canvas_to_avatar()` and `ui.attach_canvas_to_vr_rig()`. 
- The default `plane_distance` value for `ui.attach_canvas_to_vr_rig(plane_distance)` is 0.25 (was 1)
=> Set default VR rig UI canvas plane distance to 0.25

Documentation/Changelog.md, Documentation/lessons/vr/oculus_touch.md, Documentation/python/add_ons/oculus_touch.md, Documentation/python/add_ons/vr.md, Python/setup.py, Python/tdw/add_ons/oculus_touch.py, Python/tdw/add_ons/vr.py
- Added optional parameters `position` (an x, y, z dictionary) and `rotation` to the constructor of `VRRig`, `VRRig.reset()`, the constructor of `OculusTouch`, and `OculusTouch.reset()`. This fixes a "bug" in which it wasn't possible to set the position of a VR rig on the same frame as when it is spawned.
- Updated `lessons/vr/oculus_touch.md` with code examples
=> Added initial  position and rotation parameters for VR rigs

Docker/start_container.sh, Docker/start_container_audio_video.sh, Docker/start_container_xpra.sh
Hi all,
I was trying to run TDW via docker containers as explained here https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/setup/install.md#install-tdw-in-a-docker-container. 
When running the example launch script mentioned (Step 7), this error came up
`./start_container.sh: line 3: ./tdw_version.sh: No such file or directory`
I believe this might be caused by referencing a file that is no longer present in the code. I changed the docker startup scripts to follow the method used in `./Docker/pull.sh script` (https://github.com/threedworld-mit/tdw/blob/15354427161d19b6a8f437ac622012a59e78b301/Docker/pull.sh).
Please let me know if this was a mistake by my end.
All the best
=> Updated docker start scripts to use "tdw_version.py"

Documentation/Changelog.md, Documentation/python/add_ons/physics_audio_recorder.md, Python/setup.py, Python/tdw/add_ons/physics_audio_recorder.py
- Added optional parameter `device_name` to `PhysicsAudioRecorder.start()`.
=> Added optional parameter device_name to PhysicsAudioRecorder

Documentation/Changelog.md, Documentation/api/command_api.md, Documentation/lessons/video/screen_record_linux.md, Documentation/lessons/video/screen_record_osx.md, Documentation/lessons/video/screen_record_windows.md
- Fixed: `set_screen_size` doesn't wait until the window is done resizing, resulting in occasional errors in video capture commands such as `start_video_capture_windows` as well as in `send_images`.
- Fixed: `start_video_capture_osx` fails if `"audio"` is set to `False`.
| Document                                                     | Modification                                                 |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| `lessons/video/screen_record_linux.d`<br>`lessons/video/screen_record_osx.md`<br>`lessons/video/screen_record_windows.md` | Clarified how to use `log_args` to check for ffmpeg errors and listed a few common errors plus their solutions. |
=> ffmpeg bugs on OSX

Documentation/Changelog.md, Documentation/api/command_api.md
| Command                                                      | Modification                                                 |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| `start_video_capture_linux`<br>`start_video_capture_osx`<br>`start_video_capture_window` | Added an optional parameter `pixel_format` that defaults to `"yuv420p"` and set the default value of `qp` to 1 (was 0). Because of these changes, the generated .mp4 video is much more likely to be playable in programs other than VLC. |
=> Fixed: video tends to not be playable in applications other than VLC

Documentation/Changelog.md, Documentation/api/command_api.md
| Command | Description |
| --- | --- |
| `set_focal_length`         | Set the focal length of the avatar's camera. This will automatically set the field of view. |
| Command             | Modification                                                 |
| ------------------- | ------------------------------------------------------------ |
| `set_field_of_view` | Default value for `field_of_view` is now 54.43223, which matches the actual default camera field of view. |
=> Added: set_focal_length

Documentation/Changelog.md, Python/setup.py, Python/tdw/add_ons/first_person_avatar.py
Fixed: `FirstPersonAvatar` crashes due to missing `_raycast_id` parameter.
=> Fixed: FirstPersonAvatar crashes due to missing _raycast_id parameter.

Documentation/Changelog.md, Documentation/lessons/vr/oculus_touch.md, Python/example_controllers/vr/oculus_touch_axis_listener.py, Python/example_controllers/vr/oculus_touch_button_listener.py, Python/example_controllers/vr/oculus_touch_composite_object.py, Python/example_controllers/vr/oculus_touch_image_capture.py, Python/example_controllers/vr/oculus_touch_loading_screen.py, Python/example_controllers/vr/oculus_touch_output_data.py, Python/example_controllers/vr/oculus_touch_py_impact.py
- Standardized the Oculus Touch input mapping in all examples in `vr/`: Click the left control stick to quit and press Y for a new trial/scene.
| Document                     | Modification                                                 |
| ---------------------------- | ------------------------------------------------------------ |
| `lessons/vr/oculus_touch.md` | Fixed the example code to standardize Oculus Touch input mapping: Click the left control stick to quit and press Y for a new trial/scene. |
=> Standardized Oculus Touch input mapping

Documentation/Changelog.md, Python/setup.py, Python/tdw/output_data.py, Python/tdw/replicant/actions/move_by.py
- Fixed: The `arrived_at` parameter in `replicant.move_by()` and `replicant.move_to()` sometimes doesn't get applied when checking if the Replicant arrived at the target.
=> Replicant arrived_at

Documentation/Changelog.md, Python/setup.py, Python/tdw/add_ons/replicant.py, Python/tdw/replicant/actions/animate.py, Python/tdw/replicant/actions/ik_motion.py, Python/tdw/replicant/actions/move_by.py, Python/tdw/replicant/actions/move_to.py, Python/tdw/replicant/actions/reach_for.py
- Fixed: Replicant doesn't work in newer versions of Python because it imports `annotations` from `__future__`. This import has been removed.
=> Removed all __future__ imports

Documentation/Changelog.md, Python/setup.py, Python/tdw/tdw_utils.py
- Fixed: Point clouds reshape to `(3, width, height)` instead of `(3, height, width)`
=> Fixed point cloud reshaping

Documentation/Changelog.md, Python/setup.py, Python/tdw/replicant/actions/grasp.py
- Fixed: Replicant sometimes glitches if it tries to grasp a container (the container tries to parent the Replicant to itself rather than the other way around).
=> Fixed: Replicant sometimes glitches if it tries to grasp a container

Documentation/Changelog.md, Documentation/python/asset_bundle_creator/robot_creator.md, Python/tdw/asset_bundle_creator/robot_creator.py
- Fixed: `RobotCreator` can't clone a repo if the branch is named anything other than `"master"`.
=> RobotCreator branch

Documentation/Changelog.md, Python/setup.py, Python/tdw/add_ons/floorplan_floods.json
- Fixed: `FloorplanFlood` doesn't work in any `floorplan_3` scenes due to a bad key in `floorplan_floods.json`.
=> Fixed floordplan_floods.json

Documentation/Changelog.md, Documentation/lessons/core_concepts/outdoor_scenes.md, Python/setup.py, Python/tdw/metadata_libraries/scenes.json
- Removed `abandoned_factory` because the file size is too big to be useful (over 3 GB)
- Removed `floorplan_3a`, `floorplan_3b`, and `floorplan_3c` because they aren't used in the `Floorplan` add-on
=> Removed scenes

Documentation/Changelog.md, Python/setup.py, Python/tdw/metadata_libraries/models_core.json, Python/tdw/metadata_libraries/models_special.json
Marked the following models as do_not_use: vray_077_composite, vray_083_composite, vray_084_composite, vray_085_composite
Report from the model verifier: 
[models_full.txt](https://github.com/threedworld-mit/tdw/files/11824871/models_full.txt)
=> Marked composite toaster models as do_not_use

Documentation/Changelog.md, Documentation/lessons/audio/resonance_audio.md
Closes #598
| Document                           | Modification                                                 |
| ---------------------------------- | ------------------------------------------------------------ |
| `lessons/audio/resonance_audio.md` | Added a warning about trying to run Resonance Audio on Apple Silicon (it will crash the build). |
=> Added a warning about trying to run Resonance Audio on Apple Silicon

Documentation/Changelog.md, Python/screenshotter.py, Python/setup.py, Python/tdw/metadata_libraries/materials_high.json, Python/tdw/metadata_libraries/materials_low.json, Python/tdw/metadata_libraries/materials_med.json
- Removed alcantara_microfibre_brushed_right because the `materials_med.json` version caused a crash if glass_clear was also loaded.
=> Removed alcantara_microfibre_brushed_right

Documentation/Changelog.md
Closes #625 
- Fixed: `send_local_transforms` sends world-space positions and rotations.
=> Fixed: send_local_transforms sends world space positions and rotations

Documentation/Changelog.md, Documentation/lessons/clatter/cli.md, Python/example_controllers/clatter/scrape_no_controller.py, README.md
- Added: `clatter/scrape_no_controller.py` and its dependency: `clatter/Clatter.Core.dll`. This is an example of how to import Clatter directly into Python.
| Document | Modification |
| --- | --- |
| `lessons/clatter/cli.md` | Added an explanation and example of how to use Clatter.Core.dll within a Python script. |
=> Added an example of how to use Clatter.Core.dll in a Python script

Documentation/Changelog.md, Python/setup.py, Python/tdw/add_ons/proc_gen_kitchen.py, Python/tdw/proc_gen/arrangements/data/models.json
- Removed `fridge_large_composite` as a valid refrigerator in the proc gen arrangement system because it was causing crashes.
- Fixed: ProcGenKitchen can't create multiple rooms.
=> Fixed: ProcGenKitchen can't create multiple rooms.

Documentation/Changelog.md, Documentation/lessons/troubleshooting/common_errors.md, Python/tdw/controller.py
- Slight image encoding speed improvement.
- Fixed: On some computers, images are encoded upside-down. This was supposed to be fixed in the previous version but wasn't entirely. If your computer is still saving images upside-down, either add `--flip_images` to the controller path (e.g. `python3 my_controller.py --flip_images`); this will only work if `launch_build=True`. If you're on a server and need to set `launch_build=False`, add `-flip_images` to the build path (e.g. `./TDW.x86_64 -flip_images`).
- Added two optional flags to all controllers. They only work if `launch_build=True`:
- `--force_glcore42` Launch the build using OpenGL 4.2, which can fix some segfaults. If `launch_build=False`, you instead launch your build with a similar flag: `./TDW.x86_64 -force-glcore42`.
- …
=> Graphics blit

Documentation/Changelog.md, Documentation/python/asset_bundle_creator/animation_creator.md, Documentation/python/asset_bundle_creator/asset_bundle_creator.md, Documentation/python/asset_bundle_creator/composite_object_creator.md, Documentation/python/asset_bundle_creator/humanoid_creator.md, Documentation/python/asset_bundle_creator/humanoid_creator_base.md, Documentation/python/asset_bundle_creator/model_creator.md, Documentation/python/asset_bundle_creator/robot_creator.md, Python/setup.py, Python/tdw/asset_bundle_creator/asset_bundle_creator.py, Python/tdw/asset_bundle_creator/composite_object_creator.py, Python/tdw/asset_bundle_creator/humanoid_creator_base.py, Python/tdw/asset_bundle_creator/model_creator.py, Python/tdw/asset_bundle_creator/robot_creator.py
Added optional argument `targets` to each asset bundle creator (e.g. `ModelCreator`) function that creates asset bundles (e.g. `source_file_to_asset_bundles()`). If set, asset bundles for only these targets will be created. Options: `"linux"`, `"osx"`, `"windows"`, `"webgl"`. If None, defaults to `["linux", "osx", "windows"]`.
=> Added optional targets parameter to set asset bundle build targets

Documentation/Changelog.md, Python/tdw/controller.py
=> Fixed: The argument parser in Controller allows ambiguous abbreviations.

Python/example_controllers/vr/fove_calibration_test.py, Python/tdw/FBOutput/Fove.py, Python/tdw/add_ons/fove_leap_motion.py, Python/tdw/output_data.py, Python/tdw/vr_data/fove/eye.py, Python/tdw/vr_data/fove/fove_status.py
This PR merges `fove_hit_positions` into `fove_vr_calibration`, as opposed to `master`.
The changes in this PR have not been tested and require testing.
Added to `gaze_position` to `Eye` class. This is an x, y, z numpy array of the hit position of the eye's ray. The position is valid as long as the eye is looking at an object or a background scene mesh. If the eye is looking at empty space, `gaze_position` is None.
=> Gaze hit positions
